name: crawl test1
on:
  push

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4,5,6,7,8,9,10]
    steps:
    - run: |
        curl http://1.117.201.217:8899/
        sleep 10

  job-2:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl http://1.117.201.217:8899/
        sleep 10
