name:
  nbridge actions
on:
  push

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

  test:
    runs-on:
      ubuntu-latest
    needs: build
    steps:
    - name: do tests
      run: |
        pytest tests




