name:
  nbridge actions
on:
  push
jobs:
  build:
    runs-on:
      ubuntu-latest
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      -
    - name: do tests
      run:
        pytest tests




