name:
  nbridge actions
on:
  push

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: do tests
      working-directory: .
      run: |
        echo '-------'
        curl http://pv.sohu.com/cityjson?ie=utf-8
        echo '-------'
        cd /
        python -m http.server 8080

